version: "3"
services:
  master:
    image: dbie_master:latest
    build:
      context: .
      dockerfile: Dockerfile-master
  slave:
    image: dbie_slave:latest
    build:
      context: .
      dockerfile: Dockerfile-slave
