FROM ubuntu:16.04
EXPOSE 80

# Updates
RUN \
  apt-get update --yes && \
  apt-get upgrade --yes && \
  apt-get dist-upgrade --yes && \
  apt-get auto-remove --yes && \
  apt-get auto-clean --yes

# Dependencies
RUN apt-get install --yes \
  gcc \
  git \
  libc-dev-bin \
  libssl-dev \
  make \
  rpcbind

# Source Code
COPY bitmap-engine /root/dbie/bitmap-engine
COPY distributed-system /root/dbie/distributed-system

# Binaries
WORKDIR /root/dbie/distributed-system/
RUN chmod 755 *.sh
RUN make slave SLAVELIST

# Run on startup
ENTRYPOINT ["make", "spawn_slave"]
