version: "3"
services:
  dev:
    image: dbie:dev
    build:
      context: .
      dockerfile: Dockerfile-dev
  prod:
    image: dbie:prod
    depends_on:
      - dev
    build:
      context: .
      dockerfile: Dockerfile-prod
